### ISSUE TITLE
If there is a profile page which has entry as well as picker , it will be nice to show a dropdown image for visual appeal for a picker...

### ISSUE THREAD

**Issue by ithiredguns** [StephanArnas/CraftUI#1]
Steps
1) Add a icon 50x50  - "dropdown.png" to Resources/Images in the Blog_MAUI_Components project
2) In the Blog_MAUI_Components.MAUI project , add another LabelBase called "PickerLabelBase"  ( This will ensure that both regular entry and Picker can co-exist. ) . This file has the following snippet just above the activity indicator
 <Image HorizontalOptions="End" 
           VerticalOptions="Center" Source="dropdown" 
           WidthRequest="30"
           HeightRequest="30"
           Margin="0,0, 8, 0"></Image>
3) On both the PickerLabel and PickerPopupLabel xaml * xaml.cs files, inherit from PickerLabelBase instead of LabelBase Example: <base:PickerLabelBase.Resources/>

[Blog_MAUI_ComponentLibrary-articles-part_4_PULLREQUEST.zip](https://github.com/user-attachments/files/17469923/Blog_MAUI_ComponentLibrary-articles-part_4_PULLREQUEST.zip)
![image](https://github.com/user-attachments/assets/de3501c1-fd3d-4272-ad0e-7fcaada094dd)

**Comment by StephanArnas** [comment]
Hello @ithiredguns 
Thanks for the update. 
I will work on it, but I will implement a slightly different solution.
Instead of creating a base class only for PickerLabelBase, let's use our LabelBase and define a new behavior for all our component (it was part of my new article, but I took a break with holiday).
It would be the possibility to add a button with a behavior on the right side of every control.

**Comment by StephanArnas** [comment]
Hello @ithiredguns 
I’ve just responded to your issue with a full article explaining how I implemented a generic Action Icon Button for all controls derived from LabelBase.
[(Library Part 5) Extending Control Behavior with Button](https://www.stephanarnas.com/posts/extendind-control-behavior-with-button)
I suggest updating your code with my implementation to stay aligned with the evolution of this library. 
If you have any feedback, I’d be happy to hear it!
Happy coding.
